exp_dir: /ecgvae/Models/TimeDiffusion/
local: false
projectconf:
  total_limit: 2
accelerator:
  gradient_accumulation_steps: 1
  mixed_precision: 'no'
  log_with: wandb
time: 12

defaults:
  - dataloader: batch128
  - optimizer: adamw-lr4
  - loss: L2
  - lr_scheduler: cos-w100
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

train:
  num_epochs: 100
  patience: 10

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: PTBXL
    storage: null
    n_trials: 15
    n_jobs: 1
    


model-params-num_layers: 2
model-params-d_model: 64 
model-params-n_heads: 4
model-params-patch_len: 10
model-params-norm_first: false
model-params-swiglu: true
model-params-rmsnorm: true